In [ ]:
import pandas as pd
import numpy as np

#Creazione di un df

In [ ]:
np.random.seed(667)

mydata= np.random.randint(0,101,(4,3))
mydata

array([[ 85,  15,  89],
       [100,   3,  90],
       [  2,  64,   0],
       [ 36,  99,  47]])

In [ ]:
myindex=['A','B','C','D']

In [ ]:
mycolumns = ['Gennaio', 'Febbraio','Marzo']

In [ ]:
df = pd.DataFrame(data = mydata, index=myindex, columns=mycolumns)

In [ ]:
df

   Gennaio  Febbraio  Marzo
A       85        15     89
B      100         3     90
C        2        64      0
D       36        99     47

#Len

In [ ]:
len(df) #numero di righe

4

#Info, dtype per sapere la tipologia di dato

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, A to D
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Gennaio   4 non-null      int64
 1   Febbraio  4 non-null      int64
 2   Marzo     4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes

In [ ]:
df.dtypes #le stringhe, solo una tipologia di dato

Gennaio     int64
Febbraio    int64
Marzo       int64
dtype: object

In [ ]:
df = pd.read_csv('tips_complete.csv')
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

#Transponi

In [ ]:
df.describe().T #transpose (scambia righe con colonne)

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

#Shape, size, type

In [ ]:
df.shape #numero

(244, 11)

In [ ]:
df.size #numero di celle

2684

In [ ]:
df.total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
type(df['total_bill']) #la tipologia di cosa è total_bill è una Series, ovvero una colonna

pandas.core.series.Series

In [ ]:
df[['total_bill', 'tip']] #per due o più colonne doppie brackets

#Creazione di una nuova colonna

In [ ]:
df['tip_percentage'] = 100* df['tip']/df['total_bill']
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.820426
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,15.974441

In [ ]:
df['price_per_person1'] = np.round(df['total_bill'] / df['size'], 3) #round arrotondo, dopo la virgola c'è 3 che è il numero di decimali

#Impostare un indice

In [ ]:
df.set_index('Payment ID') #inplace=True in automatico, inserisco un indice, imposto Payment ID come indice ma mi fa solo vedere la preview, non lo imposta sul df

Se vado a vedere df avrò l'indice vecchio. Per impostare il nuovo indice ho due modi:
*  sovrascrivo il nuovo df facendo df = df.set_index('Payment ID')
* scrivo df.set_index('Payment ID', inplace=True)

In [ ]:
df.set_index('Payment ID', inplace=True)

#Creare una copia del df

In [ ]:
df1 = df.copy() #creo la copia del DF

#LOC/ILOC

*  iloc con i numeri/index
*  loc con i valori/stringa

Questi due esempi sono uguali:

In [ ]:
df.iloc[0] #mi fa vedere tutti i valori della prima riga

total_bill                        16.99
tip                                1.01
sex                              Female
smoker                               No
day                                 Sun
time                             Dinner
size                                  2
price_per_person                  8.495
Payer Name           Christy Cunningham
CC Number              3560325168603410
tip_percentage                 5.944673
price_per_person1                 8.495
Name: Sun2959, dtype: object

In [ ]:
df.loc['Sun2959']

total_bill                        16.99
tip                                1.01
sex                              Female
smoker                               No
day                                 Sun
time                             Dinner
size                                  2
price_per_person                  8.495
Payer Name           Christy Cunningham
CC Number              3560325168603410
tip_percentage                 5.944673
price_per_person1                 8.495
Name: Sun2959, dtype: object

#Slicing

In [ ]:
df.iloc[:4] #il 4 escluso ma iniziando da 0 sono le prime 4

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_percentage,price_per_person1
Payment ID,,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3560325168603410,5.944673,8.495
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4478071379779230,16.054159,3.447
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6011812112971322,16.658734,7.003
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4676137647685994,13.978041,11.840

In [ ]:
df.loc[['Sun2959','Sun5260']]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_percentage,price_per_person1
Payment ID,,,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.495,Christy Cunningham,3560325168603410,5.944673,8.495
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.840,Nathaniel Harris,4676137647685994,13.978041,11.840

#Droppare un elemento

*  Axis=1 è la **colonna**
*  Axis=0 è la **riga**

In [ ]:
df.drop('Sun2959', axis=0)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,tip_percentage,price_per_person1
Payment ID,,,,,,,,,,,,
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4478071379779230,16.054159,3.447
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6011812112971322,16.658734,7.003
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4676137647685994,13.978041,11.840
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4832732618637221,14.680765,6.148
Sun9679,25.29,4.71,Male,No,Sun,Dinner,4,6.322500,Erik Smith,213140353657882,18.623962,6.322
...,...,...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.676667,Michael Avila,5296068606052842,20.392697,9.677
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.590000,Monica Sanders,3506806155565404,7.358352,13.590
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.335000,Keith Wong,6011891618747196,8.822232,11.335
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.910000,Dennis Dixon,4375220550950,9.820426,8.910
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.390000,Michelle Hardin,3511451626698139,15.974441,9.390

In [ ]:
#RICORDA di mettere df= sennò non lo sovrascrive
df = df.drop('Sun2959', axis=0)

#Append

In [ ]:
first_row = df.loc['Sun4608']
first_row

total_bill                      10.34
tip                              1.66
sex                              Male
smoker                             No
day                               Sun
time                           Dinner
size                                3
price_per_person             3.446667
Payer Name             Douglas Tucker
CC Number            4478071379779230
tip_percentage              16.054159
price_per_person1               3.447
Name: Sun4608, dtype: object

In [ ]:
df.append(first_row)

#Trasformo tipologia della serie in array

In [ ]:
type(first_row)

pandas.core.series.Series

In [ ]:
array_row = df.loc['Sun4608'].values #posso anche fare first_row.values
array_row

array([10.34, 1.66, 'Male', 'No', 'Sun', 'Dinner', 3, 3.4466666666666668,
       'Douglas Tucker', 4478071379779230, 16.054158607350097, 3.447],
      dtype=object)

#Groupby

In [ ]:
df.groupby('class').count()

In [ ]:
df1

labels                  0            1           2            3
Alcohol count   59.000000    23.000000   57.000000    39.000000
        mean    12.870000    13.860000   12.475088    13.459487
        std      0.750051     0.366246    0.632430     0.663487
        min     11.450000    13.160000   11.030000    11.960000
        25%     12.330000    13.675000   12.080000    13.050000
...                   ...          ...         ...          ...
Proline min    550.000000  1185.000000  278.000000   830.000000
        25%    611.000000  1267.500000  380.000000   882.500000
        50%    660.000000  1285.000000  450.000000  1015.000000
        75%    712.000000  1412.500000  495.000000  1062.500000
        max    795.000000  1680.000000  530.000000  1150.000000

[104 rows x 4 columns]

In [ ]:
labels_df[labels_df['labels']==0]

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,labels
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,0
20,14.06,1.63,2.28,16.0,126,3.00,3.17,0.24,2.10,5.65,1.09,3.71,780,0
21,12.93,3.80,2.65,18.6,102,2.41,2.41,0.25,1.98,4.50,1.03,3.52,770,0
39,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760,0
40,13.56,1.71,2.31,16.2,117,3.15,3.29,0.34,2.34,6.13,0.95,3.38,795,0
43,13.24,3.98,2.29,17.5,103,2.64,2.63,0.32,1.66,4.36,0.82,3.00,680,0
60,12.33,1.10,2.28,16.0,101,2.05,1.09,0.63,0.41,3.27,1.25,1.67,680,0
62,13.67,1.25,1.92,18.0,94,2.10,1.79,0.32,0.73,3.80,1.23,2.46,630,0
65,12.37,1.21,2.56,18.1,98,2.42,2.65,0.37,2.08,4.60,1.19,2.30,678,0
68,13.34,0.94,2.36,17.0,110,2.53,1.30,0.55,0.42,3.17,1.02,1.93,750,0
69,12.21,1.19,1.75,16.8,151,1.85,1.28,0.14,2.50,2.85,1.28,3.07,718,0
78,12.33,0.99,1.95,14.8,136,1.90,1.85,0.35,2.76,3.40,1.06,2.31,750,0
81,12.72,1.81,2.20,18.8,86,2.20,2.53,0.26,1.77,3.90,1.16,3.14,714,0
82,12.08,1.13,2.51,24.0,78,2.00,1.58,0.40,1.40,2.20,1.31,2.72,630,0
87,11.65,1.67,2.62,26.0,88,1.92,1.61,0.40,1.34,2.60,1.36,3.21,562,0
88,11.64,2.06,2.46,21.6,84,1.95,1.69,0.48,1.35,2.80,1.00,2.75,680,0
89,12.08,1.33,2.30,23.6,70,2.20,1.59,0.42,1.38,1.74,1.07,3.21,625,0
96,11.81,2.12,2.74,21.5,134,1.60,0.99,0.14,1.56,2.50,0.95,2.26,625,0
98,12.37,1.07,2.10,18.5,88,3.52,3.75,0.24,1.95,4.50,1.04,2.77,660,0
100,12.08,2.08,1.70,17.5,97,2.23,2.17,0.26,1.40,3.30,1.27,2.96,710,0
101,12.60,1.34,1.90,18.5,88,1.45,1.36,0.29,1.35,2.45,1.04,2.77,562,0
104,12.51,1.73,1.98,20.5,85,2.20,1.92,0.32,1.48,2.94,1.04,3.57,672,0
109,11.61,1.35,2.70,20.0,94,2.74,2.92,0.29,2.49,2.65,0.96,3.26,680,0
110,11.46,3.74,1.82,19.5,107,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562,0
112,11.76,2.68,2.92,20.0,103,1.75,2.03,0.60,1.05,3.80,1.23,2.50,607,0
119,12.00,3.43,2.00,19.0,87,2.00,1.64,0.37,1.87,1.28,0.93,3.05,564,0
120,11.45,2.40,2.42,20.0,96,2.90,2.79,0.32,1.83,3.25,0.80,3.39,625,0
129,12.04,4.30,2.38,22.0,80,2.10,1.75,0.42,1.35,2.60,0.79,2.57,580,0
130,12.86,1.35,2.32,18.0,122,1.51,1.25,0.21,0.94,4.10,0.76,1.29,630,0
132,12.81,2.31,2.40,24.0,98,1.15,1.09,0.27,0.83,5.70,0.66,1.36,560,0
133,12.70,3.55,2.36,21.5,106,1.70,1.20,0.17,0.84,5.00,0.78,1.29,600,0
134,12.51,1.24,2.25,17.5,85,2.00,0.58,0.60,1.25,5.45,0.75,1.51,650,0
135,12.60,2.46,2.20,18.5,94,1.62,0.66,0.63,0.94,7.10,0.73,1.58,695,0
136,12.25,4.72,2.54,21.0,89,1.38,0.47,0.53,0.80,3.85,0.75,1.27,720,0
138,13.49,3.59,2.19,19.5,88,1.62,0.48,0.58,0.88,5.70,0.81,1.82,580,0
139,12.84,2.96,2.61,24.0,101,2.32,0.60,0.53,0.81,4.92,0.89,2.15,590,0
140,12.93,2.81,2.70,21.0,96,1.54,0.50,0.53,0.75,4.60,0.77,2.31,600,0
141,13.36,2.56,2.35,20.0,89,1.40,0.50,0.37,0.64,5.60,0.70,2.47,780,0
143,13.62,4.95,2.35,20.0,92,2.00,0.80,0.47,1.02,4.40,0.91,2.05,550,0
147,12.87,4.61,2.48,21.5,86,1.70,0.65,0.47,0.86,7.65,0.54,1.86,625,0
148,13.32,3.24,2.38,21.5,92,1.93,0.76,0.45,1.25,8.42,0.55,1.62,650,0
149,13.08,3.90,2.36,21.5,113,1.41,1.39,0.34,1.14,9.40,0.57,1.33,550,0
153,13.23,3.30,2.28,18.5,98,1.80,0.83,0.61,1.87,10.52,0.56,1.51,675,0
154,12.58,1.29,2.10,20.0,103,1.48,0.58,0.53,1.40,7.60,0.58,1.55,640,0
155,13.17,5.19,2.32,22.0,93,1.74,0.63,0.61,1.55,7.90,0.60,1.48,725,0
158,14.34,1.68,2.70,25.0,98,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660,0
159,13.48,1.67,2.64,22.5,89,2.60,1.10,0.52,2.29,11.75,0.57,1.78,620,0
161,13.69,3.26,2.54,20.0,107,1.83,0.56,0.50,0.80,5.88,0.96,1.82,680,0
162,12.85,3.27,2.58,22.0,106,1.65,0.60,0.60,0.96,5.58,0.87,2.11,570,0
163,12.96,3.45,2.35,18.5,106,1.39,0.70,0.40,0.94,5.28,0.68,1.75,675,0
164,13.78,2.76,2.30,22.0,90,1.35,0.68,0.41,1.03,9.58,0.70,1.68,615,0
166,13.45,3.70,2.60,23.0,111,1.70,0.92,0.43,1.46,10.68,0.85,1.56,695,0
167,12.82,3.37,2.30,19.5,88,1.48,0.66,0.40,0.97,10.26,0.72,1.75,685,0
168,13.58,2.58,2.69,24.5,105,1.55,0.84,0.39,1.54,8.66,0.74,1.80,750,0
169,13.40,4.60,2.86,25.0,112,1.98,0.96,0.27,1.11,8.50,0.67,1.92,630,0
172,14.16,2.51,2.48,20.0,91,1.68,0.70,0.44,1.24,9.70,0.62,1.71,660,0
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,0
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,0
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,0

In [ ]:
labels_df[labels_df['labels']==0].describe()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,labels
count,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.000000,59.0
mean,12.870000,2.697627,2.379322,20.240678,99.830508,2.027627,1.427288,0.404237,1.434915,5.551525,0.870508,2.270169,659.220339,0.0
std,0.750051,1.246264,0.274703,2.714337,15.033471,0.537428,0.868830,0.133819,0.627805,2.774268,0.226155,0.714759,67.832722,0.0
min,11.450000,0.940000,1.700000,13.200000,70.000000,1.150000,0.470000,0.140000,0.410000,1.280000,0.540000,1.270000,550.000000,0.0
25%,12.330000,1.650000,2.280000,18.500000,89.000000,1.635000,0.690000,0.305000,0.950000,3.285000,0.700000,1.675000,611.000000,0.0
50%,12.860000,2.580000,2.360000,20.000000,97.000000,1.930000,1.200000,0.400000,1.350000,4.920000,0.820000,2.110000,660.000000,0.0
75%,13.425000,3.645000,2.570000,22.000000,106.000000,2.275000,1.885000,0.525000,1.825000,7.625000,1.040000,2.870000,712.000000,0.0
max,14.340000,5.650000,2.920000,26.000000,151.000000,3.520000,3.750000,0.630000,3.580000,13.000000,1.360000,3.710000,795.000000,0.0

In [ ]:
labels[labels==-1] #per trovare dov'è il label nella colonna label con -1

128   -1
Name: labels, dtype: int64

In [ ]:
(labels==-1).sum() #per vedere quante ce ne sono

1

#Per vedere categorical e numerical features

In [ ]:
categorical_features = [col for col in train_df.columns if train_df[col].dtype==object] #per trovare le features con object come tipo di dato nelle colonne

In [ ]:
numerical_features = [col for col in train_df.columns if train_df[col].dtype!=object] #per le features numeriche

Prendi una colonna per ogni colonna nel mio train df se il tipo è oggetto

In [ ]:
[col for col in train_df.columns if train_df[col].dtype==object]

['Country', 'Status']

In [ ]:
#oppure 
train_df[categorical_features]

               Country      Status
301             Israel  Developing
400             Greece  Developing
1224            Brazil  Developing
1113          Portugal   Developed
331            Eritrea  Developing
...                ...         ...
356            Croatia   Developed
960           Suriname  Developing
812           Maldives  Developing
132           Paraguay  Developing
885   Papua New Guinea  Developing

[1047 rows x 2 columns]

#Valori nulli

```

df1 = df.fillna(df.mean()) #con la media
df['numeri']=df['numeri'].fillna(0)
df['numeri']=df['numeri'].fillna(df['numeri'].mean())
df = df.dropna() #drop delle righe con valori nulli

```


Replace:
```

df = df.replace('simbolo da rimpiazzare', 0)
```

Interpolate

```

# To replace missing values with interpolated values, for example Age
df['Age'] = df['Age'].interpolate()
```